namespace Liza.Core.Models;

/// <summary>
/// Video data extracted from YouTube
/// </summary>
[GenerateSerializer]
public class VideoData
{
    [Id(0)] public required string VideoId { get; init; }
    [Id(1)] public required string Title { get; init; }
    [Id(2)] public required string Description { get; init; }
    [Id(3)] public required DateTime PublishedAt { get; init; }
    [Id(4)] public required string ChannelId { get; init; }
    [Id(5)] public required string ChannelTitle { get; init; }
    [Id(6)] public List<string> Tags { get; init; } = [];
    [Id(7)] public string? CategoryId { get; init; }
    [Id(8)] public long ViewCount { get; init; }
    [Id(9)] public long LikeCount { get; init; }
    [Id(10)] public long CommentCount { get; init; }
    [Id(11)] public TimeSpan Duration { get; init; }
    [Id(12)] public string Definition { get; init; } = "hd";
    [Id(13)] public ThumbnailSet Thumbnails { get; init; } = new();
}

[GenerateSerializer]
public class ThumbnailSet
{
    [Id(0)] public string? Default { get; init; }
    [Id(1)] public string? Medium { get; init; }
    [Id(2)] public string? High { get; init; }
    [Id(3)] public string? MaxRes { get; init; }
}

[GenerateSerializer]
public class ChannelData
{
    [Id(0)] public required string ChannelId { get; init; }
    [Id(1)] public required string Title { get; init; }
    [Id(2)] public string Description { get; init; } = "";
    [Id(3)] public string? CustomUrl { get; init; }
    [Id(4)] public long SubscriberCount { get; init; }
    [Id(5)] public long VideoCount { get; init; }
    [Id(6)] public long ViewCount { get; init; }
    [Id(7)] public List<string> Keywords { get; init; } = [];
    [Id(8)] public ThumbnailSet Thumbnails { get; init; } = new();
}

[GenerateSerializer]
public class CommentData
{
    [Id(0)] public required string CommentId { get; init; }
    [Id(1)] public required string VideoId { get; init; }
    [Id(2)] public required string AuthorName { get; init; }
    [Id(3)] public required string Text { get; init; }
    [Id(4)] public int LikeCount { get; init; }
    [Id(5)] public DateTime PublishedAt { get; init; }
    [Id(6)] public int ReplyCount { get; init; }
    public bool IsQuestion => Text.Contains('?');
}

[GenerateSerializer]
public class TranscriptData
{
    [Id(0)] public required string VideoId { get; init; }
    [Id(1)] public string Language { get; init; } = "en";
    [Id(2)] public bool IsAutoGenerated { get; init; }
    [Id(3)] public string FullText { get; init; } = "";
    [Id(4)] public List<TranscriptSegment> Segments { get; init; } = [];
}

[GenerateSerializer]
public class TranscriptSegment
{
    [Id(0)] public double StartTime { get; init; }
    [Id(1)] public double EndTime { get; init; }
    [Id(2)] public required string Text { get; init; }
}

[GenerateSerializer]
public class KeywordData
{
    [Id(0)] public required string Keyword { get; init; }
    [Id(1)] public int SearchVolume { get; init; }
    [Id(2)] public string Competition { get; init; } = "unknown";
    [Id(3)] public int CompetitionIndex { get; init; }
    [Id(4)] public int LowBidCents { get; init; }
    [Id(5)] public int HighBidCents { get; init; }
    [Id(6)] public int TrendScore { get; init; }
    [Id(7)] public string TrendDirection { get; init; } = "stable";
    [Id(8)] public List<string> RelatedQueries { get; init; } = [];
}

[GenerateSerializer]
public class EnrichedVideo
{
    [Id(0)] public required VideoData Details { get; init; }
    [Id(1)] public TranscriptData? Transcript { get; init; }
    [Id(2)] public List<CommentData> Comments { get; init; } = [];
    [Id(3)] public ChannelData? Channel { get; init; }
    [Id(4)] public VideoRankingSignals? RankingSignals { get; init; }
}

/// <summary>
/// Ranking signals explaining why a video ranks for a keyword
/// </summary>
[GenerateSerializer]
public class VideoRankingSignals
{
    // Video-level signals
    [Id(0)] public bool KeywordInTitle { get; init; }
    [Id(1)] public bool KeywordInFirst3Words { get; init; }
    [Id(2)] public bool KeywordInDescription { get; init; }
    [Id(3)] public int TagMatchCount { get; init; }
    [Id(4)] public int TranscriptMentions { get; init; }
    [Id(5)] public double EngagementRate { get; init; }  // likes/views as percentage
    [Id(6)] public int ChannelAuthorityTier { get; init; }  // 1-5, based on subscriber count
    
    // Channel-level signals
    [Id(8)] public bool KeywordInChannelName { get; init; }  // Does channel name contain keyword?
    [Id(9)] public bool KeywordInChannelKeywords { get; init; }  // Is keyword in channel's keywords?
    [Id(10)] public int ChannelKeywordMatchCount { get; init; }  // How many channel keywords match?
    [Id(11)] public bool IsNicheChannel { get; init; }  // Channel name/keywords suggest focus on this topic
    [Id(12)] public bool KeywordInChannelDescription { get; init; }  // Keyword in channel about/description
    
    // Comment signals (audience engagement with keyword)
    [Id(13)] public int CommentKeywordMentions { get; init; }  // How many comments mention the keyword
    [Id(14)] public bool AudienceDiscussesKeyword { get; init; }  // 3+ comments mention keyword
    
    // Channel keyword authority (videos with keyword on channel over time)
    [Id(15)] public int ChannelVideosAnalyzed { get; init; }  // Total videos analyzed on channel
    [Id(16)] public int ChannelVideosWithKeyword { get; init; }  // Videos with keyword in title/tags
    [Id(17)] public double ChannelKeywordRatio { get; init; }  // % of channel videos about this keyword
    [Id(18)] public bool IsKeywordAuthority { get; init; }  // 30%+ of videos mention keyword
    
    [Id(7)] public List<string> RankingReasons { get; init; } = [];  // Human-readable explanations
}

[GenerateSerializer]
public class KeywordResearchResult
{
    [Id(0)] public required string Keyword { get; init; }
    [Id(1)] public DateTime ResearchedAt { get; init; } = DateTime.UtcNow;
    [Id(2)] public List<EnrichedVideo> Videos { get; init; } = [];
    [Id(3)] public List<string> YouTubeSuggestions { get; init; } = [];
    [Id(4)] public List<string> GoogleSuggestions { get; init; } = [];
    [Id(5)] public KeywordData? KeywordMetrics { get; init; }
    [Id(6)] public List<RedditPost> RedditPosts { get; init; } = [];
    [Id(7)] public int TotalVideoCount { get; init; }  // Total search results (before enrichment limit)
}

[GenerateSerializer]
public class RedditPost
{
    [Id(0)] public required string PostId { get; init; }
    [Id(1)] public required string Title { get; init; }
    [Id(2)] public string? SelfText { get; init; }
    [Id(3)] public required string Subreddit { get; init; }
    [Id(4)] public int Score { get; init; }
    [Id(5)] public int NumComments { get; init; }
    [Id(6)] public DateTime CreatedAt { get; init; }
    [Id(7)] public required string Url { get; init; }
}

[GenerateSerializer]
public class TrendData
{
    [Id(0)] public required string Keyword { get; init; }
    [Id(1)] public int InterestScore { get; init; }
    [Id(2)] public string Direction { get; init; } = "stable";
    [Id(3)] public List<TrendPoint> Timeline { get; init; } = [];
    [Id(4)] public List<string> RelatedQueries { get; init; } = [];
    [Id(5)] public List<string> RisingQueries { get; init; } = [];
}

[GenerateSerializer]
public class TrendPoint
{
    [Id(0)] public DateTime Date { get; init; }
    [Id(1)] public int Value { get; init; }
}

/// <summary>
/// Google Video Search result
/// </summary>
[GenerateSerializer]
public class GoogleVideoResult
{
    [Id(0)] public required string Title { get; init; }
    [Id(1)] public required string Url { get; init; }
    [Id(2)] public string? Description { get; init; }
    [Id(3)] public string? Source { get; init; }
    [Id(4)] public string? Duration { get; init; }
    [Id(5)] public string? ThumbnailUrl { get; init; }
    [Id(6)] public DateTime? PublishedAt { get; init; }
    [Id(7)] public string? Channel { get; init; }
    [Id(8)] public string? ViewCount { get; init; }
}

