namespace Liza.Api.GraphQL.Types;

using Liza.Core.Models;

/// <summary>
/// GraphQL types for video data
/// </summary>
public class VideoType : ObjectType<VideoData>
{
    protected override void Configure(IObjectTypeDescriptor<VideoData> descriptor)
    {
        descriptor.Description("YouTube video data");
        
        descriptor.Field(v => v.VideoId)
            .Description("Unique YouTube video ID");
        
        descriptor.Field(v => v.Duration)
            .Description("Video duration")
            .Type<StringType>()
            .Resolve(ctx => ctx.Parent<VideoData>().Duration.ToString(@"hh\:mm\:ss"));
        
        descriptor.Field(v => v.ViewCount)
            .Description("Total view count");
        
        descriptor.Field(v => v.Thumbnails)
            .Description("Video thumbnail URLs");
    }
}

public class EnrichedVideoType : ObjectType<EnrichedVideo>
{
    protected override void Configure(IObjectTypeDescriptor<EnrichedVideo> descriptor)
    {
        descriptor.Description("Video with full extracted data");
        
        descriptor.Field(v => v.Details)
            .Description("Basic video metadata");
        
        descriptor.Field(v => v.Transcript)
            .Description("Video transcript/captions");
        
        descriptor.Field(v => v.Comments)
            .Description("Top video comments");
        
        descriptor.Field(v => v.Channel)
            .Description("Channel information");
    }
}

public class TranscriptType : ObjectType<TranscriptData>
{
    protected override void Configure(IObjectTypeDescriptor<TranscriptData> descriptor)
    {
        descriptor.Description("Video transcript data");
        
        descriptor.Field(t => t.FullText)
            .Description("Complete transcript text");
        
        descriptor.Field(t => t.IsAutoGenerated)
            .Description("Whether the transcript was auto-generated");
    }
}

public class CommentType : ObjectType<CommentData>
{
    protected override void Configure(IObjectTypeDescriptor<CommentData> descriptor)
    {
        descriptor.Description("YouTube comment");
        
        descriptor.Field(c => c.IsQuestion)
            .Description("Whether the comment contains a question");
    }
}

public class ChannelType : ObjectType<ChannelData>
{
    protected override void Configure(IObjectTypeDescriptor<ChannelData> descriptor)
    {
        descriptor.Description("YouTube channel data");
    }
}

public class KeywordResearchResultType : ObjectType<KeywordResearchResult>
{
    protected override void Configure(IObjectTypeDescriptor<KeywordResearchResult> descriptor)
    {
        descriptor.Description("Complete keyword research result");
        
        descriptor.Field(r => r.Keyword)
            .Description("The researched keyword");
        
        descriptor.Field(r => r.Videos)
            .Description("Top videos for this keyword");
        
        descriptor.Field(r => r.YouTubeSuggestions)
            .Description("YouTube autocomplete suggestions");
        
        descriptor.Field(r => r.GoogleSuggestions)
            .Description("Google autocomplete suggestions");
    }
}

public class TrendDataType : ObjectType<TrendData>
{
    protected override void Configure(IObjectTypeDescriptor<TrendData> descriptor)
    {
        descriptor.Description("Google Trends data");
        
        descriptor.Field(t => t.InterestScore)
            .Description("Interest score from 0-100");
        
        descriptor.Field(t => t.Direction)
            .Description("Trend direction: rising, stable, or declining");
    }
}
